export const lectures = [
    {
      id: 1,
      thumbnail: "/images/thumb.png",
      country: "일본",
      title: "일본 여행 완벽 가이드",
      description: "일본 여행의 모든 것",
      price: "89,000원",
      mileage: "500",
      students: "1,234",
      chapters: 4,
      createdAt: "2024.04.15",
      isPublic: true,
    },
    {
      id: 2,
      thumbnail: "/images/thumb.png",
      country: "프랑스",
      title: "파리 완전 정복 2024",
      description: "파리의 모든 것을 담은 강의",
      price: "85,000원",
      mileage: "300",
      students: "934",
      chapters: 5,
      createdAt: "2024.04.10",
      isPublic: true,
    },
    {
      id: 3,
      thumbnail: "/images/thumb.png",
      country: "미국",
      title: "뉴욕 자유여행 가이드",
      description: "뉴욕 여행 준비하기",
      price: "89,000원",
      mileage: "00",
      students: "892",
      chapters: 3,
      createdAt: "2024.03.28",
      isPublic: false,
    },
  ];
